plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'maven-publish'
    id 'jacoco'
}

group = 'fr.cgtlabs'
version = '1.0.2-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-restclient'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	annotationProcessor 'org.projectlombok:lombok:1.18.42'
	compileOnly 'org.projectlombok:lombok:1.18.42'

    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'dev.blaauwendraad:json-masker:1.1.4'

    testImplementation 'org.springframework.boot:spring-boot-starter-restclient-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}


jar {
    enabled = true
    archiveClassifier = ''
}

bootJar {
    enabled = false
}

publishing {
    publications {
        create('mavenJava', MavenPublication) {
            from components.java
            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }
        }
    }
}

jacoco {
    toolVersion = "0.8.15"
}

tasks.named('test') {
	useJUnitPlatform()
    finalizedBy 'jacocoTestReport'
}

tasks.named('jacocoTestReport', JacocoReport) {
    dependsOn tasks.test
    reports {
        xml.required = true
        csv.required = false
        html.required = true
    }

    classDirectories.setFrom(
            fileTree(layout.buildDirectory.dir('classes/java/main'))
    )

    sourceDirectories.setFrom(files(
            "$project.projectDir/src/main/java"
    ))
    executionData.setFrom(fileTree(layout.buildDirectory.dir('jacoco')).include('*.exec'))
}