mainPackage=fr.cgtlabs.springboot.logging
org.gradle.configuration-cache=true

# GitHub Packages credentials (DO NOT COMMIT THIS FILE TO GIT)
# Replace YOUR_GITHUB_USERNAME with your GitHub username
# Replace YOUR_GITHUB_TOKEN with your GitHub Personal Access Token (PAT) with 'write:packages' and 'repo' scopes
githubUsername=kixalt
githubToken=